import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('next').NextConfig} */
const nextConfig = {
  poweredByHeader: false,
  outputFileTracingRoot: __dirname,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "animenew.com.br" },
      { protocol: "https", hostname: "www.animenew.com.br" },
      { protocol: "https", hostname: "animenewsnetwork.com" },
      { protocol: "https", hostname: "www.animenewsnetwork.com" },
      { protocol: "https", hostname: "cdn.animenewsnetwork.com" },
      { protocol: "https", hostname: "animecorner.me" },
      { protocol: "https", hostname: "www.animecorner.me" },
      { protocol: "https", hostname: "static.animecorner.me" },
      { protocol: "https", hostname: "anitrendz.net" },
      { protocol: "https", hostname: "www.anitrendz.net" },
      { protocol: "https", hostname: "myanimelist.net" },
      { protocol: "https", hostname: "cdn.myanimelist.net" },
      { protocol: "https", hostname: "otakuusamagazine.com" },
      { protocol: "https", hostname: "www.otakuusamagazine.com" },
      { protocol: "https", hostname: "animeherald.com" },
      { protocol: "https", hostname: "www.animeherald.com" },
      { protocol: "https", hostname: "animeuknews.net" },
      { protocol: "https", hostname: "www.animeuknews.net" },
      { protocol: "https", hostname: "otakunews.com" },
      { protocol: "https", hostname: "www.otakunews.com" },
      { protocol: "https", hostname: "siliconera.com" },
      { protocol: "https", hostname: "www.siliconera.com" },
      { protocol: "https", hostname: "crunchyroll.com" },
      { protocol: "https", hostname: "www.crunchyroll.com" },
      { protocol: "https", hostname: "imgsrv.crunchyroll.com" },
      { protocol: "https", hostname: "gematsu.com" },
      { protocol: "https", hostname: "www.gematsu.com" },
      { protocol: "https", hostname: "nintendolife.com" },
      { protocol: "https", hostname: "www.nintendolife.com" },
      { protocol: "https", hostname: "assets.nintendolife.com" },
      { protocol: "https", hostname: "pcgamer.com" },
      { protocol: "https", hostname: "www.pcgamer.com" },
      { protocol: "https", hostname: "cdn.mos.cms.futurecdn.net" },
      { protocol: "https", hostname: "eurogamer.net" },
      { protocol: "https", hostname: "www.eurogamer.net" },
      { protocol: "https", hostname: "assetsio.gnwcdn.com" },
      { protocol: "https", hostname: "rockpapershotgun.com" },
      { protocol: "https", hostname: "www.rockpapershotgun.com" },
      { protocol: "https", hostname: "ign.com" },
      { protocol: "https", hostname: "www.ign.com" },
      { protocol: "https", hostname: "assets-prd.ignimgs.com" },
      { protocol: "https", hostname: "gamespot.com" },
      { protocol: "https", hostname: "www.gamespot.com" },
      { protocol: "https", hostname: "static1.gamespot.com" },
      { protocol: "https", hostname: "aftermath.site" },
      { protocol: "https", hostname: "www.aftermath.site" },
      { protocol: "https", hostname: "kakuchopurei.com" },
      { protocol: "https", hostname: "www.kakuchopurei.com" },
      { protocol: "https", hostname: "kongbakpao.com" },
      { protocol: "https", hostname: "www.kongbakpao.com" },
    ],
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 604800,
  },
  turbopack: {
    root: __dirname,
  },
};

export default nextConfig;
